---
abstract: 'Keeps track of progress status'
author:
  - 'Steven Humphrey'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Plack::Test: '0'
  Test::More: '0'
  Test::Warnings: '0'
  YAML: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer2-Plugin-ProgressStatus
recommends:
  JSON::XS: '0'
requires:
  Dancer2: '0.09'
  Digest::MD5: '0'
  JSON: '0'
  Path::Tiny: '0.037'
resources:
  bugtracker: https://github.com/shumphrey/Dancer2-Plugin-ProgressStatus/issues
  repository: https://github.com/shumphrey/Dancer2-Plugin-ProgressStatus
version: '0.015'
